FROM alpine:3.11.6 as build

RUN apk update && \
    apk add alpine-sdk clang cmake openssl openssl-dev

ADD . /home/git-semantic-versioning
WORKDIR /home/git-semantic-versioning

RUN mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=release ../ && \
    make -j8

FROM alpine:3.11.6

COPY --from=build /home/git-semantic-versioning/build/git_semver /home/git-semantic-versioning/git_semver
COPY --from=build /home/git-semantic-versioning/build/git_semver /usr/local/bin/git_semver
