name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Build the Docker image.
      run: docker build . --tag rcosnita/git-semantic-versioning:latest
    - name: Build the Docker image for alpine.
      run: docker build . -f Dockefile-alpine --tag rcosnita/git-semantic-versioning:latest-alpine
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker semver image.
      run: |
        mkdir gitsemver_tool
        docker run -i --rm \
          -v $(pwd)/gitsemver_tool:/home/gitsemver_tool:rw \
          --entrypoint "/bin/sh" \
          rcosnita/git-semantic-versioning:latest << COMMANDS
          cp /usr/local/bin/git_semver /home/gitsemver_tool
        COMMANDS
        docker tag rcosnita/git-semantic-versioning:latest rcosnita/git-semantic-versioning:$(./gitsemver_tool/git_semver -shalength 8)
        docker push rcosnita/git-semantic-versioning:$(./gitsemver_tool/git_semver -shalength 8)
    - name: Push the tagged Docker image
      run: docker push rcosnita/git-semantic-versioning:latest
    - name: Push the tagged Docker image alpine
      run: docker push rcosnita/git-semantic-versioning:latest-alpine

  build-release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags')
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Get current tag name
      uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Build the Docker image.
      run: docker build . --tag rcosnita/git-semantic-versioning:$GIT_TAG_NAME
    - name: Build the Docker image alpine.
      run: docker build . -f Dockerfile-alpine --tag rcosnita/git-semantic-versioning:$GIT_TAG_NAME-alpine
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the tagged Docker image
      run: docker push rcosnita/git-semantic-versioning:$GIT_TAG_NAME
    - name: Push the tagged Docker image alpine
      run: docker push rcosnita/git-semantic-versioning:$GIT_TAG_NAME-alpine
